---

- name: Configuration of my computer
  hosts: localhost
  sudo: yes
  vars_files:
    - vars/config.yml
    - vars/apt.yml
    - vars/checker.yml
    - vars/deb.yml
    - vars/gitconfig.yml
    - vars/node.yml
  roles:
#    - { role: kosssi.checker, tags: checker }
    - { role: kosssi.gitconfig, tags: gitconfig, sudo: false }
    - { role: kosssi.apt, tags: apt }
    - { role: kosssi.phpstorm, tags: phpstorm }
    - { role: kosssi.composer, tags: composer }
    - { role: ajsalminen.deb_get, tags: deb }
    - { role: ahmednuaman.nvm-ahmed, tags: nvm, sudo: false }
